_target_: mourat.resolvers.paper_resolver.PaperResolver
_partial_: true
title_similarity_threshold: 0.9
arxiv_client:
  _target_: mourat.clients.arxiv.ArxivClient
  user_agent: ${metadata_api_user_agent}
  regular_delay_seconds: 3.0