_target_: pydantic_ai.models.openai.OpenAIChatModel
_recursive_: true
model_name: nvidia/nemotron-3-nano-30b-a3b:free
provider:
  _target_: pydantic_ai.providers.openai.OpenAIProvider
  base_url: https://openrouter.ai/api/v1
  api_key: ${oc.env:OPENROUTER_API_KEY}
