hydra_root: ${oc.env:MOURAT_HYDRA_PATH, /tmp/mourat_hydra}
hydra_dir: ${user_settings.hydra_root}/${now:%Y-%m-%d}/${now:%H-%M-%S}
result_dir: ${user_settings.hydra_dir}
db_path: ${oc.env:MOURAT_DB_PATH, null}

caila_api_key: ${oc.env:CAILA_API_KEY, null}
openalex_api_key: ${oc.env:OPENALEX_API_KEY, null}  # set to your OpenAlex premium API key string to use the authenticated tier

reddit:
    client_id: ${oc.env:MOURAT_REDDIT_CLIENT_ID, null}
    client_secret: ${oc.env:MOURAT_REDDIT_CLIENT_SECRET, null}
    user_agent: python 
